### PR TITLE
feat(aoh):utilize habitat source by Jung et al., 2020

### PR DESCRIPTION
**Pull request by suuf**
Hello @jeffreyhanson 😄,

I wanted to utilize this library to calculate AOH with the habitat data by Jung et al., 2020. I saw most the functionality was already covered by you, so I made these small changes. Not sure what your contribution best practices are - I tried to follow some generic practices. Please let me know if anything else would be required for this pull request. 

Hope it's all good 👍

### CODE REVIEW

**Comment by jeffreyhanson** [comment]
Hi @suuf,

Thanks for reaching out and preparing this PR - I really appreicate it!

It sounds like you want to create AOH data using the Jung Level 1 habitat dataset - is that right? If so, this should be possible using the current version of the package. To acheive this, you'll need to (1) download the habitat data (using `get_jung_lvl1_habitat_data()`), (2) import the crosswalk data, and (3) use these datasets as arguments for `create_spp_aoh_data()`.

I've included an example below showing how to do this using simulated species data. Since the IUCN red list API is currently down, I haven't been able to test it - but hopefully it should work with only a few minor tweaks. What do you think? Does this provide all the functionality you're looking for?

---- 


```
# load package
library(aoh)

# specify settings for data processing
output_dir <- tempdir()                       # folder to save AOH data
cache_dir <- rappdirs::user_data_dir("aoh")   # persistent storage location
n_threads <- parallel::detectCores() - 1      # speed up analysis

# create cache directory if needed
if (!file.exists(cache_dir)) {
  dir.create(cache_dir, showWarnings = FALSE, recursive = TRUE)
}

# find file path for example range data following IUCN Red List data format
## N.B., the range data were not obtained from the IUCN Red List,
## and were instead based on data from GBIF (https://www.gbif.org/)
path <- system.file("extdata", "EXAMPLE_SPECIES.zip", package = "aoh")

# import data
data(crosswalk_jung_lvl1_data)
spp_range_data <- read_spp_range_data(path)
jung_data <- get_jung_lvl1_habitat_data(dir = cache_dir)

# create species information data
spp_info_data <- create_spp_info_data(
  x = spp_range_data,
  cache_dir = cache_dir
)

# create Area of Habitat data for species
# N.B., the default based on Jung level 1 dataset
spp_aoh_data <- create_spp_aoh_data(
  x = spp_info_data,
  output_dir = output_dir,
  n_threads = n_threads,
  habitat_data = jung_data,
  crosswalk_data = crosswalk_jung_lvl1_data,
  cache_dir = cache_dir
)

# print result
print(spp_aoh_data)
```

**Comment by suuf** [comment]
Hi again,

Thanks for your reply. Your solution seems to work as I would like it to - but I will check it for sure once the IUCN API is back.

Thank you for your time 😃

**Comment by jeffreyhanson** [comment]
Ok great! Let me know if this doesn't provide the functionality you're looking for or if you have any follow up questions?

**Comment by jeffreyhanson** [comment]
Hi @suuf, I just wanted to follow up and ask if you still needed this PR merged to get the desired functionality? Or can you get the desired functionality by customizing the parameters (i.e., like in the example)?

**Comment by suuf** [comment]
Hi there. The parameter customization in your suggestion works for me, thank you very much! Sorry I forgot to close the PR 🙂

**Comment by jeffreyhanson** [comment]
Awesome - glad to hear it worked for you. No worries!

**Pull request closed without merging**
